export const TYPE_COLORS = {
  normal: "#9099A1",
  fire: "#FF4D3B",
  water: "#4D90FF",
  electric: "#FFD700",
  grass: "#3EBD5E",
  ice: "#5BC8D8",
  fighting: "#CC3300",
  poison: "#9B44B7",
  ground: "#C9A22E",
  flying: "#8899FF",
  psychic: "#FF5B8D",
  bug: "#8DAE0F",
  rock: "#A69139",
  ghost: "#5A4880",
  dragon: "#6A40E8",
  dark: "#5A4030",
  steel: "#9898BA",
  fairy: "#DB7EC8",
};

export const STAT_ABBR = {
  hp: "PS",
  attack: "ATQ",
  defense: "DEF",
  "special-attack": "SpA",
  "special-defense": "SpD",
  speed: "VEL",
};

export const TYPE_CHART = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: {
    fire: 0.5,
    water: 0.5,
    rock: 0.5,
    dragon: 0.5,
    grass: 2,
    ice: 2,
    bug: 2,
    steel: 2,
  },
  water: { water: 0.5, grass: 0.5, dragon: 0.5, fire: 2, ground: 2, rock: 2 },
  electric: {
    electric: 0.5,
    grass: 0.5,
    dragon: 0.5,
    ground: 0,
    water: 2,
    flying: 2,
  },
  grass: {
    fire: 0.5,
    grass: 0.5,
    poison: 0.5,
    flying: 0.5,
    bug: 0.5,
    dragon: 0.5,
    steel: 0.5,
    water: 2,
    ground: 2,
    rock: 2,
  },
  ice: {
    water: 0.5,
    ice: 0.5,
    steel: 0.5,
    grass: 2,
    ground: 2,
    flying: 2,
    dragon: 2,
  },
  fighting: {
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    fairy: 0.5,
    ghost: 0,
    normal: 2,
    ice: 2,
    rock: 2,
    dark: 2,
    steel: 2,
  },
  poison: {
    poison: 0.5,
    ground: 0.5,
    rock: 0.5,
    ghost: 0.5,
    steel: 0,
    grass: 2,
    fairy: 2,
  },
  ground: {
    grass: 0.5,
    bug: 0.5,
    flying: 0,
    fire: 2,
    electric: 2,
    poison: 2,
    rock: 2,
    steel: 2,
  },
  flying: {
    electric: 0.5,
    rock: 0.5,
    steel: 0.5,
    grass: 2,
    fighting: 2,
    bug: 2,
  },
  psychic: { psychic: 0.5, steel: 0.5, dark: 0, fighting: 2, poison: 2 },
  bug: {
    fire: 0.5,
    fighting: 0.5,
    flying: 0.5,
    ghost: 0.5,
    steel: 0.5,
    fairy: 0.5,
    grass: 2,
    psychic: 2,
    dark: 2,
  },
  rock: {
    fighting: 0.5,
    ground: 0.5,
    steel: 0.5,
    fire: 2,
    ice: 2,
    flying: 2,
    bug: 2,
  },
  ghost: { normal: 0, dark: 0.5, ghost: 2, psychic: 2 },
  dragon: { steel: 0.5, fairy: 0, dragon: 2 },
  dark: { fighting: 0.5, dark: 0.5, fairy: 0.5, ghost: 2, psychic: 2 },
  steel: {
    fire: 0.5,
    water: 0.5,
    electric: 0.5,
    steel: 0.5,
    ice: 2,
    rock: 2,
    fairy: 2,
  },
  fairy: {
    fire: 0.5,
    poison: 0.5,
    steel: 0.5,
    fighting: 2,
    dragon: 2,
    dark: 2,
  },
};

export const STATUS_ICON = {
  burn: "🔥",
  poison: "☠️",
  paralysis: "⚡",
  sleep: "💤",
  freeze: "🧊",
};

export const STATUS_COLOR = {
  burn: "#FF4D3B",
  poison: "#9B44B7",
  paralysis: "#FFD700",
  sleep: "#4D90FF",
  freeze: "#5BC8D8",
};

export const CAT_ICON = { physical: "⚔️", special: "✨", status: "○" };

export const MOVE_COLORS = ["#FF4D3B", "#4D90FF", "#3EBD5E", "#FFD700"];
